version: '3'

services:
  pharmacy-recommendation-redis:
    container_name: pharmacy-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: namyunho/pharmacy-recommendation-redis
    ports:
      - "6379:6379"
  mysql:
    container_name: pharmacy-recommendation-database
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_HOST: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: "pharmacy-recommendation"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--character-set-server=utf8mb4"
      - "--skip-character-set-client-handshake"
  pharmacy-recommendation-app:
    container_name: pharmacy-recommendation-app
    build: .
    depends_on: # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행시킨다.
      - mysql
      - pharmacy-recommendation-redis
    image: namyunho/pharmacy-recommendation-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always # depends on은 실행 순서만 컨트롤 할뿐,
    # 컨테이너 안의 서비스가 실행가능한 상태인지까지는 확인 하지 않기 때문에
    # DB 또는 Redis가 아직 실행가능한 상태가 아니여서 실패하는 경우 재시작 하도록 설정